src/main/java/org/ici/stats/domain/CurrentSelection.java
package org.ici.stats.domain;

import com.google.common.base.Joiner;
import com.google.common.base.Strings;
import com.google.common.collect.Lists;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;

import java.util.List;

/**
 * Current selection of report options
 */
public class CurrentSelection {
    // default to current month
    private Period period = Period.CurrentMonth;
    private List<DataPoint> dataPoints = Lists.newArrayList();
    private List<Category> categories = Lists.newArrayList();
    private List<MethodOfSale> methodOfSales = Lists.newArrayList();
    private DateTime startDate;
    private DateTime endDate;
    private Report report;

    public Period getPeriod() {
        return period;
    }

    public boolean isCurrentMonth() {
        return Period.CurrentMonth.equals( period );
    }

    public boolean isMonthly() {
        return Period.Monthly.equals( period );
    }

    public boolean isQuarterly() {
        return Period.Quarterly.equals( period );
    }

    public boolean isAnnual() {
        return Period.Annual.equals( period );
    }

    public void setPeriod(Period period) {
        this.period = period;
    }

    public List<DataPoint> getDataPoints() {
        return dataPoints;
    }

    public void setDataPoints(List<DataPoint> dataPoints) {
        this.dataPoints = dataPoints;
    }

    @SuppressWarnings("unused")
    public String getDataPointsStr() {
        if ( getDataPoints() == null ) {
            return "";
        }
        List<String> names = Lists.newArrayList();
        for (DataPoint dataPoint : getDataPoints()) {
            names.add( dataPoint.getFullName() );
        }
        return Joiner.on( "<br/> ").join( names );
    }

    @SuppressWarnings("unused")
    public String getFundType() {
        if (  isETF() ) {
            return "ETF";
        } else {
            return "Mutual Fund";
        }
    }

    public boolean isETF() {
        return ( ReportType.ALL_ETF_REPORTS.contains( report.getReportType() ));
    }

    @SuppressWarnings("unused")
    public boolean isReadyToRun() {
        return ( !getDataPoints().isEmpty() && !getCategories().isEmpty() && !Strings.isNullOrEmpty(getDateRange() ));
    }

    /**
     * used by the sidebar jsp
     * @return flag to denote whether we can allow mos selection
     */
    @SuppressWarnings("unused")
    public boolean isMosAvailable() {
        boolean available = true;
        List<DataPoint> points = getDataPoints();
        if (points != null ) {
            for (DataPoint point : points) {
                if ( !point.isMosCompatible() ) {
                    available = false;
                    break;
                }
            }
        }
        return available;
    }


    public List<Category> getCategories() {
        return categories;
    }

    public void setCategories(List<Category> categories) {
        this.categories = categories;
    }

    /**
     * used by the sidebar jsp
     * @return comma separated list of methods of categories
     */
    @SuppressWarnings("unused")
    public String getCategoriesStr() {
        if ( getCategories() == null ) {
            return "";
        }
        List<String> names = Lists.newArrayList();
        for (Category cat : getCategories()) {
            names.add( cat.getName() );
        }
        return Joiner.on( "<br/> ").join( names );
    }

    public DateTime getStartDate() {
        return startDate;
    }

    public void setStartDate(DateTime startDate) {
        this.startDate = startDate;
    }

    public DateTime getEndDate() {
        return endDate;
    }

    public void setEndDate(DateTime endDate) {
        this.endDate = endDate;
    }

    public List<MethodOfSale> getMethodsOfSale() {
        return methodOfSales;
    }

    public void setMethodsOfSale(List<MethodOfSale> methodOfSales) {
        this.methodOfSales = methodOfSales;
    }

    /**
     * used by the sidebar jsp
     * @return comma separated list of methods of sale
     */
    @SuppressWarnings("unused")
    public String getMethodsOfSaleStr() {
        if ( getMethodsOfSale() == null ) {
            return "";
        }
        List<String> names = Lists.newArrayList();
        for (MethodOfSale mos : getMethodsOfSale()) {
            names.add( mos.getName() );
        }
        return Joiner.on( "<br/> ").join( names );
    }

    private final static org.joda.time.format.DateTimeFormatter monthlyFormat = DateTimeFormat.forPattern("MMMM yyyy" );

    /**
     * used by the sidebar jsp
     * @return nice view of the selected dates
     */
    @SuppressWarnings("unused")
    public String getDateRange() {
        if ( getPeriod() == null ) {
            return null;
        }
        switch ( getPeriod() ) {
            case Annual:
                return Integer.toString(getStartDate().year().get()) + " - " + Integer.toString(getEndDate().year().get());
            case Quarterly:
                return "Quarter";
            case CurrentMonth:
                return "Current Month Totals (" + monthlyFormat.print( getEndDate() ) + ")";
            case Monthly:
            default:
                return monthlyFormat.print( getStartDate() ) + " - " + monthlyFormat.print( getEndDate() );
        }
    }

    public Report getReport() {
        return report;
    }

    public void setReport(Report _report) {
        this.report = _report;
    }
}

src/main/java/org/ici/stats/domain/Report.java
package org.ici.stats.domain;

import com.google.common.base.Function;
import com.google.common.collect.FluentIterable;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.Maps;
import org.ici.stats.utils.CategoryUtils;
import org.joda.time.DateTime;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

public class Report implements ReportDefinition, Serializable {
    private final ReportType type;
    private final List<Category> categories;
    private final List<Category> allCategories;
    private final List<DataPointGroup> dataPoints;
    private final List<DataPoint> allDataPoints;
    private final List<MethodOfSale> methodsOfSale;
    private final List<MethodOfSale> allMethodsOfSale;
    private final Map<String,Category> categoryMap;
    private final Map<String,MethodOfSale> methodOfSaleMap;
    private final DateTime startDate;
    private final DateTime mosStartDate;
    private final String footNote;
    private final boolean allowPartialQuarters;

    private final Map<DataPoint, String> fieldNameMap;
    private final Map<DataPoint, String> fieldEquationMap;

    public Report(ReportType type, List<Category> categories, List<DataPointGroup> dataPoints, List<MethodOfSale> methodsOfSale, DateTime startDate, DateTime mosStartDate, String footNote, boolean allowPartialQuarters, Map<DataPoint, String> fieldNameMap, Map<DataPoint, String> fieldEquationMap) {
        this.type = type;
        this.categories = categories;
        this.dataPoints = dataPoints;
        this.methodsOfSale = methodsOfSale;
        this.startDate = startDate;
        this.mosStartDate = mosStartDate;
        this.footNote = footNote;
        this.allowPartialQuarters = allowPartialQuarters;
        this.allCategories = ImmutableList.copyOf(CategoryUtils.getFlatList( categories ));
        this.fieldNameMap = fieldNameMap;
        this.fieldEquationMap = fieldEquationMap;

        Map<String,Category> catMap = Maps.newHashMap();
        for (Category cat : allCategories) {
            catMap.put( cat.getName(), cat );
        }
        categoryMap = ImmutableMap.copyOf( catMap );
        allMethodsOfSale = ImmutableList.copyOf( MosUtils.getFlatList( methodsOfSale ));

        Map<String,MethodOfSale> mosMap = Maps.newHashMap();
        for (MethodOfSale mos : allMethodsOfSale) {
            mosMap.put( mos.getName(), mos );
        }
        methodOfSaleMap = ImmutableMap.copyOf( mosMap );

        // create a "flattened" list of data points
        FluentIterable<DataPoint> pointsIter = FluentIterable.from( dataPoints ).transformAndConcat(new Function<DataPointGroup, Iterable<DataPoint>>() {
            @Override
            public Iterable<DataPoint> apply(DataPointGroup dataPointGroup) {
                return dataPointGroup.getPoints();
            }
        });
        allDataPoints = ImmutableList.copyOf( pointsIter );
    }



    public ReportType getReportType() {
        return type;
    }

    public List<Category> getCategories() {
        return categories;
    }

    public Category getCategoryByName( String name ) {
        return categoryMap.get( name );
    }

    public List<Category> getAllCategories() { return allCategories; }

    public List<DataPoint> getAllDataPoints() {
        return allDataPoints;
    }

    public List<MethodOfSale> getAllMethodsOfSale() {
        return allMethodsOfSale;
    }

    public MethodOfSale getMethodOfSaleByName( String name ) {
        return methodOfSaleMap.get( name );
    }

    public List<DataPointGroup> getDataPointGroups() {
        return dataPoints;
    }

    @Override
    public List<MethodOfSale> getMethodsOfSale() {
        return methodsOfSale;
    }

    @Override
    public String getFieldName(DataPoint point) {
        return fieldNameMap.get( point );
    }

    @Override
    public String getFieldEquation(DataPoint point) {
        return fieldEquationMap.get( point );
    }

    public String getFootNote() {
        return footNote;
    }

    public String getName() {
        return type.getName();
    }

    @Override
    public DateTime getStartDate() {
        return startDate;
    }

    @Override
    public DateTime getMosStartDate() {
        return mosStartDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Report report = (Report) o;

        return type == report.type;
    }

    @Override
    public int hashCode() {
        return type != null ? type.hashCode() : 0;
    }
}

src/main/java/org/ici/stats/domain/ReportResult.java
package org.ici.stats.domain;

import org.ici.stats.services.ReportUtils;

import java.util.List;

public class ReportResult {
    private final ReportRequest request;
    private final String fundCountLabel;
    private final List<ReportRow> data;

    public ReportResult(ReportRequest request, List<ReportRow> rows, String fundCountLabel) {
        this.request = request;
        this.data = rows;
        this.fundCountLabel = fundCountLabel;
    }

    public ReportRequest getRequest() {
        return request;
    }

    public List<ReportRow> getData() {
        return data;
    }

    public String getDisplayDate( ReportRow row ) {
        return ReportUtils.getDisplayDate( request.getPeriod(), row.getDatePeriod(), row.getYear() );
    }

    public String getFundCountLabel() {
        return fundCountLabel;
    }

    public boolean isShowFundCounts() {
        return ReportType.MutualFunds.equals( request.getReportType() );
    }

}

src/main/java/org/ici/stats/servlets/DataPointServlet.java
package org.ici.stats.servlets;

import com.google.common.collect.Lists;
import com.google.inject.Singleton;
import org.ici.stats.domain.*;
import org.ici.stats.domain.CurrentSelection;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;

@Singleton
public class DataPointServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        handleRequest( req, resp );
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        handleRequest( req, resp );
    }

    private void handleRequest(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        // ok, now to redirect to where we need to go
        String actionParam = req.getParameter( "action" );
        if ( "next".equalsIgnoreCase( actionParam )) {
            updateDataPoints( req );
            // need to switch this up depending on what we're working with
            CurrentSelection currentSelection = ServletUtils.getCurrentSelection(req);
            ReportType type = currentSelection.getReport().getReportType();
            if (ReportType.MutualFunds.equals( type )) {
                resp.sendRedirect( req.getContextPath() + "/mf/objectives");
            } else if ( ReportType.ETF.equals( type )) {
                resp.sendRedirect( req.getContextPath() + "/etf/objectives");
            } else {
                resp.sendRedirect( req.getContextPath() + "/specialty/objectives");
            }
        } else {
            req.setAttribute("monthly", ReportType.MutualFunds);
            req.setAttribute("monthlySpecialty", ReportType.SORTED_SPECIAL_REPORTS);
            req.getRequestDispatcher("/WEB-INF/pages/datapoints.jsp" ).forward( req, resp );
        }
    }

    private void updateDataPoints( HttpServletRequest req ) {
        // see if we have any data points that need saving
        CurrentSelection currentSelection = ServletUtils.getCurrentSelection(req);
        String[] dataPointsParam = req.getParameterValues("dataPoints");
        List<DataPoint> points;
        if (dataPointsParam == null || dataPointsParam.length == 0) {
            points = Lists.newArrayList();
        } else {
            points = DataPoint.getDataPoints(dataPointsParam);
        }
        currentSelection.setDataPoints( points );

        // see if we need to clear out and of our existing selection based on the current report
        // needed since when we change the report, some of the old data points are submitted at the same time
        updateDataPointsBasedOnReport( currentSelection.getDataPoints(), currentSelection.getReport() );
        updateCategoriesBasedOnReport( currentSelection.getCategories(), currentSelection.getReport() );
        updateMOSBasedOnReport( currentSelection.getMethodsOfSale(), currentSelection.getReport() );

        ServletUtils.updateCurrentSelection( req, currentSelection );
    }

    private static void updateCategoriesBasedOnReport(List<Category> categories, Report report) {
        Iterator<Category> catIter = categories.iterator();
        List<Category> reportCats = report.getCategories();
        while( catIter.hasNext() ) {
            Category curCat = catIter.next();
            if ( !reportCats.contains( curCat )) {
                catIter.remove();
            }
        }
    }

    private static void updateMOSBasedOnReport(List<MethodOfSale> methodsOfSale, Report report) {
        Iterator<MethodOfSale> mosIter = methodsOfSale.iterator();
        List<MethodOfSale> reportMos = report.getMethodsOfSale();
        while( mosIter.hasNext() ) {
            MethodOfSale curMos = mosIter.next();
            if ( !reportMos.contains( curMos )) {
                mosIter.remove();
            }
        }
    }

    private static void updateDataPointsBasedOnReport(List<DataPoint> points, Report currentReport) {
        Iterator<DataPoint> pointIter = points.iterator();
        List<DataPoint> reportPoints = currentReport.getAllDataPoints();
        while( pointIter.hasNext() ) {
            DataPoint curPoint = pointIter.next();
            if ( !reportPoints.contains( curPoint )) {
                pointIter.remove();
            }
        }
    }
}

src/main/webapp/WEB-INF/pages/datapoints.jsp
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib prefix="ici" uri="/WEB-INF/tld/ici.tld" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<t:page>
    <jsp:attribute name="header">
        <script type="text/javascript">
            function setSelectedReport(value) {
                document.getElementById("selectedReport").value = value;
                document.getElementById("stats_form").submit();
                console.log("submitted");
            }

            function selectAll() {
                $('input:checkbox').prop('checked', true);
            }

            function unselectAll() {
                $('input:checkbox').prop('checked', false);
            }
        </script>
    </jsp:attribute>
    <jsp:attribute name="title">
        3.  Choose Data Points
    </jsp:attribute>
    <jsp:body>
        <form method="post" id="stats_form" class="ui form">
            <div class="ui middle aligned two column centered grid">
                <div class="row">
                    <div class="column">
                        <c:forEach var="dataPointGroup" items="${sessionScope.currentSelection.report.dataPointGroups}">
                            <h5 class="ui header">${dataPointGroup.name}</h5>
                            <c:forEach var="dataPoint" items="${dataPointGroup.points}">
                                <div class="field">
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="dataPoints" id="${ici:jsSafe( dataPoint.fullName)}"
                                               value="${dataPoint.fullName}" <c:if
                                                test="${ici:contains( sessionScope.currentSelection.dataPoints, dataPoint)}"> checked="checked" </c:if> />
                                        <label for="${ici:jsSafe( dataPoint.fullName)}">${dataPoint.fullName} <c:if
                                                test="${!dataPoint.mosCompatible}"> * </c:if></label>
                                    </div>
                                </div>
                            </c:forEach>
                        </c:forEach>
                        <a href="#" onclick="selectAll()" class="ui button">Select All</a>
                        <a href="#" onclick="unselectAll()" class="ui button">Unselect All</a>
                    </div>
                    <div class="column"><input class="ui button" type="submit" name="action" value="Next"/></div>
                </div>
            </div>
        </form>
    </jsp:body>
</t:page>

src/main/webapp/WEB-INF/pages/dates.jsp
    <%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib prefix="ici" uri="/WEB-INF/tld/ici.tld" %>
    <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
    <t:page>
    <jsp:attribute name="title">5.  Choose Date Parameters</jsp:attribute>
    <jsp:body>
        <form method="post" class="form ui">
                <div class="field">
                    <div class="ui radio checkbox">
                        <c:choose>
                            <c:when test="${sessionScope.currentSelection.currentMonth}">
                                <input type="radio" name="reportPeriod" value="current" checked="checked">
                            </c:when>
                            <c:otherwise>
                                <input type="radio" name="reportPeriod" value="current">
                            </c:otherwise>
                        </c:choose>
                        <label>Current Month Totals (${currentMonth})</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <c:choose>
                            <c:when test="${sessionScope.currentSelection.annual}">
                                <input type="radio" name="reportPeriod" value="annual" checked="checked">
                            </c:when>
                            <c:otherwise>
                                <input type="radio" name="reportPeriod" value="annual">
                            </c:otherwise>
                        </c:choose>
                        <label>Annual Totals - ${firstAnnual} to Present (${currentAnnual})</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <c:choose>
                            <c:when test="${sessionScope.currentSelection.quarterly}">
                                <input type="radio" name="reportPeriod" value="quarterly" checked="checked">
                            </c:when>
                            <c:otherwise>
                                <input type="radio" name="reportPeriod" value="quarterly">
                            </c:otherwise>
                        </c:choose>
                        <label>Quarterly Totals - ${firstQuarter} to Present (${currentQuarter})</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <c:choose>
                            <c:when test="${sessionScope.currentSelection.monthly}">
                                <input type="radio" name="reportPeriod" value="range" checked="checked">
                            </c:when>
                            <c:otherwise>
                                <input type="radio" name="reportPeriod" value="range">
                            </c:otherwise>
                        </c:choose>
                        <label>Custom Date Range</label>
                    </div>
                </div>
                <div class="fields">
                    <div class="field">
                        <label>From month</label>
                        <select name="fromMonth" class="ui dropdown">
                            <c:forEach var="month" items="${months}" varStatus="status">
                                <c:set var="selected"></c:set>
                                <c:if test="${sessionScope.currentSelection.startDate != null && sessionScope.currentSelection.monthly && sessionScope.currentSelection.startDate.monthOfYear == status.count}">
                                    <c:set var="selected">selected</c:set>
                                </c:if>
                                <option ${selected} value="${status.count}">${month}</option>
                            </c:forEach>
                        </select>
                    </div>
                    <div class="field">
                        <label>Year</label>
                        <select name="fromYear" class="ui dropdown">
                            <c:forEach var="year" items="${years}">
                                <c:set var="selected"></c:set>
                                <c:if test="${sessionScope.currentSelection.startDate != null && sessionScope.currentSelection.monthly && sessionScope.currentSelection.startDate.year == year}">
                                    <c:set var="selected">selected</c:set>
                                </c:if>
                                <option ${selected} value="${year}">${year}</option>
                            </c:forEach>
                        </select>
                    </div>
                    <div class="field">
                        <label>To month</label>
                        <select name="toMonth" class="ui dropdown">
                            <c:forEach var="month" items="${months}" varStatus="status">
                                <c:set var="selected"></c:set>
                                <c:if test="${sessionScope.currentSelection.endDate != null && sessionScope.currentSelection.monthly && sessionScope.currentSelection.endDate.monthOfYear == status.count}">
                                    <c:set var="selected">selected</c:set>
                                </c:if>
                                <option ${selected} value="${status.count}">${month}</option>
                            </c:forEach>
                        </select>
                    </div>
                    <div class="field">
                        <label>Year</label>
                        <select name="toYear">
                            <c:forEach var="year" items="${years}">
                                <c:set var="selected"></c:set>
                                <c:if test="${sessionScope.currentSelection.endDate != null && sessionScope.currentSelection.monthly && sessionScope.currentSelection.endDate.year == year}">
                                    <c:set var="selected">selected</c:set>
                                </c:if>
                                <option ${selected} value="${year}">${year}</option>
                            </c:forEach>
                        </select>
                    </div>
                </div>
            <div><input type="submit" name="action" value="Run" class="ui button"></div>
        </form>
    </jsp:body>
</t:page>

src/main/webapp/WEB-INF/pages/mf_objectives.jsp
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib prefix="ici" uri="/WEB-INF/tld/ici.tld" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<t:page>
    <jsp:attribute name="header">
    <script type="text/javascript">
        $(document).ready(function () {
            $("select[name='categoryLevel']").change(function () {
                $("#stats_form").submit();
            });
        })
    </script>
        <script type="text/javascript" src="${pageContext.request.contextPath}/js/expand_collapse.js"></script>
    </jsp:attribute>
    <jsp:attribute name="title">
        4.  Choose Investment Objective
    </jsp:attribute>
    <jsp:body>
            <div class="ui segment basic"><a href="http://www.ici.org/research/stats/iob_update/iob_definitions">See Objective Category Definitions</a></div>
        <form method="post" id="stats_form" class="ui form">
            <c:choose>
                <c:when test="${sessionScope.currentSelection.mosAvailable}">
                    <c:set var="columns">three</c:set>
                </c:when>
                <c:otherwise>
                    <c:set var="columns">two</c:set>
                </c:otherwise>
            </c:choose>

            <c:if test="${!empty(errorMessage)}">
                <div class="ui inverted red segment">
                    <p>${errorMessage}</p>
                </div>
            </c:if>
            <div class="ui ${columns} column grid">
                <div class="column">
                    <h3 class="ui header">Choose a category view</h3>
                    <select name="categoryLevel" class="ui dropdown">
                        <option value="macro" <c:if test="${categoryLevel == 'macro'}"> selected="selected" </c:if>>
                            Level 3 - Macro
                        </option>
                        <option value="composite"
                                <c:if test="${categoryLevel == 'composite'}"> selected="selected" </c:if>>Level 4 -
                            Composite
                        </option>
                        <option value="objectives"
                                <c:if test="${categoryLevel == 'objectives'}"> selected="selected"</c:if>>Level 5 -
                            Objectives
                        </option>
                        <option value="hierarchy"
                                <c:if test="${categoryLevel == 'hierarchy'}"> selected="selected" </c:if>>Display
                            Complete Hierarchy
                        </option>
                    </select>
                    <h5 class="ui header">Check the investment objectives you wish to see.</h5>
                    <c:choose>
                        <c:when test="${categoryLevel == 'hierarchy'}">
                            <div class="ui list">
                                <c:forEach var="category" items="${categories}">
                                    <t:tree category="${category}"></t:tree>
                                </c:forEach>
                            </div>
                        </c:when>
                        <c:otherwise>
                            <c:forEach var="category" items="${categories}">
                                <div class="field">
                                    <div class="ui checkbox">
                                        <input type="checkbox" name="selectedCategories" value="${category.name}"
                                        <c:if test="${ici:contains(sessionScope.currentSelection.categories, category )}"> checked="checked"</c:if>>
                                        <label>${category.name}</label>
                                    </div>
                                </div>
                            </c:forEach>
                        </c:otherwise>
                    </c:choose>
                </div>
                <c:if test="${sessionScope.currentSelection.mosAvailable}">
                    <div class="column">
                        <h3>Method Of Sales (Optional)</h3>
                        <p>Method of sales breakouts are only available for high-level categories.</p>
                        <c:forEach var="mos" items="${sessionScope.currentSelection.report.methodsOfSale}">
                            <div class="field">
                                <div class="ui checkbox"><input type="checkbox" name="selectedMos" value="${mos.name}"
                                <c:if test="${ici:contains(sessionScope.currentSelection.methodsOfSale, mos)}"> checked="checked" </c:if>><label>${mos.name}</label>
                                </div>
                            </div>
                        </c:forEach>
                    </div>
                </c:if>
                <div class="column">
                    <input type="submit" name="action" value="Next" class="ui button">
                </div>
            </div>
        </form>
    </jsp:body>
</t:page>

src/main/webapp/WEB-INF/pages/report.jsp
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib prefix="ici" uri="/WEB-INF/tld/ici.tld" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<t:page>
    <jsp:attribute name="title">
        Final Report
    </jsp:attribute>
    <jsp:body>
    <form class="ui form">
        <table id="stats_results" class="ui very compact table striped">
            <thead>
            <tr>
                <th>Date</th>
                <th>Category</th>
                <c:if test="${result.showFundCounts}">
                    <th>${result.fundCountLabel}</th>
                </c:if>
                <c:forEach var="dataPoint" items="${result.request.dataPoints}">
                    <th class="ui right aligned">${dataPoint.fullName}</th>
                </c:forEach>
            </tr>
            </thead>
            <tbody>
            <c:forEach var="row" items="${result.data}">
                <tr>
                    <td>${result.getDisplayDate(row)}</td>
                    <td>${row.category}</td>
                    <c:if test="${result.showFundCounts}">
                        <td>${row.fundCount}</td>
                    </c:if>
                    <c:forEach var="dataPoint" items="${result.request.dataPoints}">
                        <td class="ui right aligned">
                            <fmt:formatNumber type="number" value="${row.valueMap[dataPoint]}"/>
                        </td>
                    </c:forEach>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </form>
    </jsp:body>
</t:page>